baseURL = "https://www.segall.io/"
languageCode = "en-us"
title = "Roy Segall | Computerised dreames"
theme = "tahini"
publishDir = "docs"

[imaging]
# Default JPEG quality setting. Default is 75.
quality = 75
